### ISSUE TITLE
org-clock dependency

### ISSUE THREAD

**Issue by kaushalmodi** [takaxp/org-tree-slide#12]
Hi,

Thanks for developing this package. After installing this package, I noticed that my emacs load time went up considerably because of `org-clock` dependency. I reviewed the source code and saw that the portion using `org-clock` functions is commented out but the require is still is place.

How do you plan to use `org-clock` in presentations? I see that `org-timer` is also required. Is there a way around using those two packages?

Thanks.

**Comment by takaxp** [comment]
Thank you for your comments.

`org-timer' is required when users start presentation by `org-tree-slide-play-with-timer' which will kick a timer and count down time for finishing their presentation within appropriate duration, they can understand the remaining time in mode line. It is good idea to move the `require' within the  `org-tree-slide-play-with-timer'. If you do not use `org-tree-slide-play-with-timer', you can remove it.

`org-clock' is loaded, as you mentioned, currently for test use so it can be removed. The original requirement is to check time allocation for each slide in a presentation, but I have already found an alternative way by adding some hooks. So you can also remove it.

I'll update this package soon. Could you provide some information to understand the time saving after you removed `(require \'org-clock') and `(require \'org-timer)'

**Comment by kaushalmodi** [comment]
Here is the init load time as measured by the [`benchmark-init`](https://github.com/dholm/benchmark-init-el) package when I use the Melpa verison of `org-tree-slide` and using a plain-old `require`.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6378170/9330227a-bcf7-11e4-87f9-ac1e72f1b544.png)

As you see `org-clock` is dominating the load time.

Here is the load time for the exact same init with the only difference that I have commented out the `(require 'org-clock)` from your package and I am using `autoload` via `use-package`:

```el
;; org-tree-slide
(use-package org-tree-slide
    :load-path "elisp/org-tree-slide"
    :commands (org-tree-slide-mode)
    :init
    (progn
      (bind-keys
       :map modi-mode-map
       ("<C-S-f8>" . org-tree-slide-mode)))
    :config
    (progn
      (setq org-tree-slide-slide-in-effect nil)
      (bind-keys
       :map org-tree-slide-mode-map
       ("p" . org-tree-slide-move-previous-tree)
       ("n" . org-tree-slide-move-next-tree)
       ("q" . org-tree-slide-mode))))
```

![clipboard02](https://cloud.githubusercontent.com/assets/3578197/6378173/97823b56-bcf7-11e4-8319-a19d995a6ccd.png)

**Comment by takaxp** [comment]
Thank you so much. It is very useful information but the result is little strange for me because `org-clock` is not so huge package compared to `org`. The loading time of `org` is 78 or 123[ms] but `org-clock` requires 4498[ms], it is toooo long! I'm not familiar with `benchmark-init` so I cannot say anything more, but the actual overhead of loading `org-clock` may be around 20[ms], which is checked in my local environment.

Any way, you can use `defer: t` option in your `use-package` setting for `org-tree-slide`. Then `org-tree-slide` and also `org-clock` will be loaded when you hit `<C-S-f8>`.

I'm ready to ship my new code with hiding `org-clock` load, it will be distributed through MELPA soon.

**Comment by takaxp** [comment]
The new code is distributed through MEPLA. I just commented out `org-clock`. `org-timer` is still required to count down your presentation. If you find an additional issue, please create a new issue ticket.
