### ISSUE TITLE
Start From Current Subtree (option)

### ISSUE THREAD

**Issue by commonman** [takaxp/org-tree-slide#18]
I am a teacher and I use org-tree-slide to show part of my lesson plans to the students via projector.  

It would be very useful if I could have the option to start at the 'slide' corresponding to where my cursor currently is, since it is often only a few parts of the whole outline that I want to show.

Thanks for this cool piece of software.

**Comment by takaxp** [comment]
Thanks to your comment and using org-tree-slide.
If my understanding is correct, it is already possible to control the starting slide if you set  `org-tree-slide-cursor-init` to `nil`.
Could you please put the following line to your emacs configuration file.

``
(setq org-tree-slide-cursor-init nil)
``

And kick org-tree-slide when the cursor on a slide you want to start.

The cursor will also be kept the position, actually on the top of heading, if you quit org-tree-slide.

**Comment by commonman** [comment]
That works great.  And I'm also glad it keeps the cursor position when it finished org-tree-slide.  This makes it easy to do a momentary low-fuss presentation, and get back to the whole buffer.
