### ISSUE TITLE
Moving backwards

### ISSUE THREAD

**Issue by jagrg** [takaxp/org-tree-slide#22]
I was expecting `org-tree-slide-move-previous-tree` to reverse the cycle of `org-tree-slide-move-next-tree`, but it doesn't. I know we can select a different heading from the content slide, but I find the following more intuitive. Maybe you have a different opinion.

```
forward               backward
|                     |
SLIDE1 --> SLIDE2 --> CONTENT --> SLIDE2 --> SLIDE1...
[1/2]      [2/2]      [2/2]       [2/2]      [1/2]
```

Another issue of moving backwards is that the point moves to the beginning of the buffer. Why not keep it at the beginning of the heading instead, like `org-tree-slide-move-next-tree`?

**Comment by takaxp** [comment]
Thanks to your feedback.

For the first question, you want to say, after you call `org-tree-slide-content` and move the cursor to a heading in an org buffer, `org-tree-slide-move-next-tree` resumes the presentation with the same slide. `org-tree-slide-move-previous-tree`, however, resumes it with the previous slide. Is this correct?

I believe that is a design problem. I will refine the CONTENT mode if my understanding is correct.

For the second question, I reproduced it when the slide header is displayed. I'll try to fix it. Thanks.

**Comment by jagrg** [comment]
I'm referring to `org-tree-slide-move-previous-tree` and the way it is used to navigate slides. With the current code, if you enable `org-tree-slide-mode` and move forward the cycle is:

`SLIDE1 --> SLIDE2 --> CONTENT --> SLIDE1 --> etc...`

What I'm saying is that the same needs to happen when moving backwards, so that pressing `C-<` on SLIDE1 reverses the cycle:

`SLIDE1 --> CONTENT --> SLIDE2 --> SLIDE1 --> etc...`

**Comment by jagrg** [comment]
BTW, this is the configuration I'm currently using:

```emacs-lisp
(use-package org-tree-slide
  :config
  (bind-key "<f8>" 'org-tree-slide-mode org-mode-map)
  (bind-keys :map org-tree-slide-mode-map
	     ("<right>" . org-tree-slide-move-next-tree)
	     ("<left>" . org-tree-slide-move-previous-tree))
  (setq org-tree-slide-slide-in-effect nil)
  (setq org-tree-slide-fold-subtrees-skipped nil)
```

**Comment by takaxp** [comment]
Ok. now I understand what you want.
Actually, I will change the forwarding cycle including CONTENT mode as an option item, the default value is `nil`, since I did not intend the behaviour like cycle.
The function just provides an automatic CONTENT mode transition when user finish the presentation like Microsoft PowerPoint.
Or do you have strong demand such a forward and backward cycle?

**Comment by jagrg** [comment]
I'm not demanding anything, my friend, and never will. This is just a suggestion, but I suspect that adding CONTENT as a variable should be enough. There's no need to cycle as long as we can move backwards from the last slide.

**Comment by takaxp** [comment]
Good. Many thanks to your comments. And sorry for my slow development, but I don't forget your previous requests.

**Comment by jagrg** [comment]
No problem. If you push the branch, I'd be happy to test it.
