### ISSUE TITLE
heading-emphasis

### ISSUE THREAD

**Issue by FrancescoCadei** [takaxp/org-tree-slide#28]
Hi, when i `(setq-default org-tree-slide-heading-emphasis t)` first livel title (*) are not emphasis, it works only from second livel (**).

![image](https://user-images.githubusercontent.com/25520099/45141622-ad08cf00-b1b6-11e8-89a2-fc8174cb390a.png)

**Comment by takaxp** [comment]
Hi @FrancescoCadei,

Right... I don't have any ideas why I implemented so...
I'll fix this soon. Thank you for your report :)

**Comment by takaxp** [comment]
Now I expanded supporting heading levels for level-1(`*`) and level-4(`****`) in https://github.com/takaxp/org-tree-slide/commit/3f1d646eb1988d0250248834d260212858200173#diff-ed3e1c1851bc85a78e80615b6d74b091.
Will be also distributed from MELPA. Enjoy!
