### ISSUE TITLE
org-tree-slide-header-overlay-face does not update upon theme change

### ISSUE THREAD

**Issue by protesilaos** [takaxp/org-tree-slide#38]
Hello and thank you for providing this!

I have encountered an issue with `org-tree-slide-header-overlay-face`, where it retains the styles of the theme that was active when `org-tree-slide-mode` was first enabled.  This means that if I try to switch between themes the document's header looks out of place.

Steps to reproduce this:

+ From the command line run `emacs -Q`
+ Evaluate `(load-file "/path/to/org-tree-slide.el")`
+ Then `(require 'org-tree-slide)`
+ Now visit an Org file, like one with the following contents:

```
#+TITLE: This is a test
#+AUTHOR: Just an author

* Testing the header overlay face

* Heading 2

* Heading 3
```

+ `M-x org-tree-slide-mode`
+ Now try to load another theme, e.g., `M-x load-theme RET tango-dark RET`.

This is what you get before and after loading the theme:

![Screenshot from 2020-12-22 08-06-39](https://user-images.githubusercontent.com/12828033/102856257-cccb6c00-442e-11eb-9fdb-d8186ddbd41c.png)

![Screenshot from 2020-12-22 08-06-47](https://user-images.githubusercontent.com/12828033/102856260-cdfc9900-442e-11eb-9a95-22f6a8cf7139.png)

My understanding is that the cause is the way `org-tree-slide-header-overlay-face` attains its attributes.

```elisp
(defface org-tree-slide-header-overlay-face
  `((t (:bold t :foreground ,(face-foreground 'default)
              :background ,(face-background 'default))))
  "Face for org-tree-slide--header-overlay"
  :group 'org-tree-slide)
```

Here is a rewrite that should deliver the same intent:

```elisp
(defface org-tree-slide-header-overlay-face '((t :weight bold))
  "Face for org-tree-slide--header-overlay"
  :group 'org-tree-slide)
```

Which works in my example when swithing to another theme:

![Screenshot from 2020-12-22 08-17-13](https://user-images.githubusercontent.com/12828033/102856275-d359e380-442e-11eb-8780-8c68ab453352.png)

Can you reproduce this?  What do you think?

Thank you for your attention!

**Comment by takaxp** [comment]
Yes. You are right. I know this issue and still thinking about the best solution.

One possible way is to provide a helper function to change the header theme appropriately when user change their theme.

```
  (defun org-tree-slide-reload-header-face ()
    (face-spec-set 'org-tree-slide-header-overlay-face
                   `((t (:bold t
                               :foreground ,(face-foreground 'default)
                               :background ,(face-background 'default))))))
```

And also provide an advice to `enable-theme` so that `org-tree-slide-reload-header-face` is called in the advice function. 

```
(defun ad:enable-theme (f theme)
  "Extend `enable-theme'.
F is the original function.
THEME is identical to the original arguments."
  (funcall f theme)
  (when (eq theme 'user)
    (run-hooks 'after-enable-theme-hook)))

(advice-add 'enable-theme :around #'ad:enable-theme)

(add-hook 'after-enable-theme-hook #'org-tree-slide-reload-header-face)
``` 

I have already implemented such hook in another package named https://github.com/takaxp/ah. Note that in this packages the hook name is `ah-after-enable-theme-hook`.

At this stage, I'm planing to integrate only `org-tree-slide-reload-header-face` to `org-tree-slide.el` and provide some instruction in README about how to use the helper function as I described in this GitHub issue.

**Comment by protesilaos** [comment]
Thank you for the detailed answer!

> At this stage, I'm planing to integrate only org-tree-slide-reload-header-face to org-tree-slide.el and provide some instruction in README about how to use the helper function as I described in this GitHub issue.

Is there some compelling reason why this face requires the extra setup?  My understanding is that any face that does not set a background/foreground (and any other properties) automatically falls back to the `default` face.  Maybe though there is some extra layer here, so apologies if I have missed it.

**Comment by takaxp** [comment]
Sorry I didn't reply to your question. Indeed, it should be ok not providing background/foreground setting but when using `hl-line.el` with `org-tree-slide` the header color is covered by a setting for `hl-line`. So I previously decided to apply the default background/foreground colors.

However I think you are right and I rethink it should be provided with `nil` as the default. Any additional comments on this?

I'll implement the auto configurator as I mentioned in this thread, which is as an optional for user who use `hl-line.el` including me.

**Comment by takaxp** [comment]
Now I found a good way to resolve this issue by applying `'((t :inherit default))` as the default value to `org-tree-slide-header-overlay-face`.

**Comment by protesilaos** [comment]
Thank you!
