### ISSUE TITLE
Export presentation as PDF?

### ISSUE THREAD

**Issue by manuel-arguelles** [takaxp/org-tree-slide#39]
Hi,

Is there anyway to export the presentation as a PDF (or html)?

**Comment by takaxp** [comment]
I didn't implement specific functions for `org-tree-slide` to export as PDF or HTML file but you can use such functionality provided by some external packages. For instance, `org-reveal` can create a rich HTML slides. For export the presentation as a PDF file, then you could use [org beamer](https://orgmode.org/worg/exporters/beamer/tutorial.html) integrated as default in `org-mode`.

**Comment by manuel-arguelles** [comment]
Thanks!
