### ISSUE TITLE
Not showing picture when using #+ATTR_* attributes

### ISSUE THREAD

**Issue by mpas** [takaxp/org-tree-slide#41]
I am trying to use org-mode and org-tree-slide. The challenge i have is that images are not displayed when using #+ATTR_* flags to rescale the image.. Am i missing something?? When starting the presentation i enabled image display so in the buffer they are scaled but whenever i start the presentation the images are blank when using an `ATTR` attribute.

```
* slide with picture without attr (shows picture)

[[file:~/img.png]]

* slide with picture and attr (does not show picture)

#+ATTR_ORG: :width 200
[[file:~/img.png]]
```

**Comment by takaxp** [comment]
Is the second image with ATTR_ORG shown in an org buffer before starting presentation by org-tree-slide?

**Comment by mpas** [comment]
Yes it is, before going to present I enable "org-toggle-inline-images"

![image](https://user-images.githubusercontent.com/139094/134010061-5f04359d-ef3e-4a77-bceb-468144955e3c.png)

**Comment by mpas** [comment]
When preseting i get this reponse..

![image](https://user-images.githubusercontent.com/139094/134010204-f6ad6eef-a87d-4d59-ac34-ec15044dc917.png)
![image](https://user-images.githubusercontent.com/139094/134010232-a844b38c-5031-45bf-8eba-3e128fe04302.png)

**Comment by mpas** [comment]
The example given i tried "ATTR_HTML" but it gives the same result

**Comment by takaxp** [comment]
Thank you for providing me additional information.
I think "ATTR_HTML" is not the option for this issue. How about M-x org-redisplay-inline-images after starting the presentation?

And could you provide the version information of Emacs and Org Mode you are using?

Currently, I couldn't reproduce the issue, the attached image shows two scaled images in an org buffer with org-tree-slide in Emacs 28.0.50 and Org 9.4.5.

<img width="688" alt="Screen Shot 2021-09-20 at 22 33 49" src="https://user-images.githubusercontent.com/136673/134011744-1bd47b11-6538-4d64-b291-e9d091bb190f.png">

**Comment by mpas** [comment]
org-redisplay-inline-images after the presentation has no effect in my case. Maybe it is related to my setup somehow.

Emacs version 27.2
Org mode version 9.5

I am using the latest Doom Emacs by the way. 

![Untitled](https://user-images.githubusercontent.com/139094/134014391-95aa9cec-a200-44bd-a662-8647d15da745.gif)

**Comment by takaxp** [comment]
Thanks, if the image is not shown when you just hit M-x org-narrow-to-subtree, then org-tree-slide is not the cause of the issue. Additionally, in the example you kindly provided, a module to center the content may be used. It is worth trying without the module if my guess is correct.

Note: M-x widen can disable narrowing of a tree.

<img width="688" alt="Screen Shot 2021-09-20 at 23 21 41" src="https://user-images.githubusercontent.com/136673/134018809-85a2dcf0-2465-49d4-ba77-fdd632165187.png">

**Comment by mpas** [comment]
I will try with all modules disabled except org-mode

**Comment by mpas** [comment]
I disabled all modules with no luck. I also tried org-present and checked if it has the same behaviour. org-present displays the images with the attr elements normally. Not sure how i can help you to track down the issue.

**Comment by takaxp** [comment]
First of all, thanks to you for checking many cases so far. I think it is little bit hard for me to resolve this issue in a short period. I'll try to use doom emacs and check the status as soon as possible. Sorry for taking time to resolve this issue. If you will find any hits, please let me know. I'll keep this issue open.

**Comment by mpas** [comment]
I will do my best to find any hints! Thanks for the reply!

**Comment by takaxp** [comment]
Thank! I didn't know doom emacs has a configuration for org-tree-slide. I'll see other code for further understanding for all doom emacs users :)
