### ISSUE TITLE
Question: Is it supposed to show the #+ATTR line when viewing the presentation?

### ISSUE THREAD

**Issue by mpas** [takaxp/org-tree-slide#42]
Hi there, having a small question. When I use org-tree-slide in doom emacs and show the presentation the #+ATTR line is visible in the presentation. Is this intended behaviour?

The original org document
![image](https://user-images.githubusercontent.com/139094/135822281-e856cd40-44db-417c-bbce-3e5f40822f18.png)

In presentation mode where i would expect that the #+ATTR would be hidden in the presentation
![image](https://user-images.githubusercontent.com/139094/135822306-37384147-6077-4690-9a57-d40194306097.png)

**Comment by takaxp** [comment]
Yes. The line is not hidden by org-tree-slide.

**Comment by takaxp** [comment]
FYI: The face for the line is `org-meta-line`. So if you add functions to change the face and add the functions to hooks defined in org-tree-slide, then the visibility could be controlled.

**Comment by takaxp** [comment]
`https://github.com/vapniks/hide-lines/blob/master/hide-lines.el` could be useful to this request. I use this package to hide "BEGIN_SRC" and "END_SRC" in a presentation.

**Comment by mpas** [comment]
Would be a great solution, but when I try to hide the #+ATTR_HTML using the regex: ^\#\+ATTR_HTML is seems to delete also the picture. 

![hidelines-with-regex](https://user-images.githubusercontent.com/139094/136141744-0c9e342b-cdbb-48f3-9c86-e3966ad28ab3.gif)

**Comment by mpas** [comment]
Again works like a charm!! I would never have been able to come up with this piece of code! So thanks a lot! Issue can be closed if you want! Again thanks for the great work!
