### ISSUE TITLE
Using full window space in mac os x

### ISSUE THREAD

**Issue by iluvatar1** [takaxp/org-tree-slide#45]
Hi, thanks for the very useful package. Will it be possible to use all the frame/window space when presenting with org-tree-slide? Currently I am getting just a centered region. I have also installed and played with moom but it does not fixes the problem.
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/1454267/143690566-5727ef8d-2057-493f-8a91-b38008018a23.png">

**Comment by takaxp** [comment]
Hi. I don't use Doom Emacs but it seems depending on the setting of margins. Could you provide me a screenshot when using org mode but not activating `org-tree-slide-mode`?

**Comment by iluvatar1** [comment]
Hi, sure. This is the original org file in my emacs
<img width="963" alt="image" src="https://user-images.githubusercontent.com/1454267/143729378-f87310cb-f219-41f9-b4b8-bb532154d73d.png">

An this is just after calling org-tree-slide-mode
<img width="963" alt="image" src="https://user-images.githubusercontent.com/1454267/143729402-c1f65ae8-40a8-40fb-9ea8-9aa43757a20b.png">

**Comment by takaxp** [comment]
OK, thanks. so something is executed when starting `org-tree-slide-mode` in Doom Emacs. Is it possible to check the value `org-tree-slide-play-hook`, `org-tree-slide-before-narrow-hook` and `org-tree-slide-after-narrow-hook` after activating `org-tree-slide`? Normally, you can check it by typing `M-: org-tree-slide-play-hook`.

**Comment by takaxp** [comment]
Doom Emacs uses such hooks maybe it is the reason why the issue was occurred. I will start to investigate a solution but it is another way to consult with experts of Doom Emacs.


https://github.com/hlissner/doom-emacs/blob/f0ba6c99b26b0bf23495323a3097cab7d057ea3d/modules/lang/org/contrib/present.el#L38

**Comment by iluvatar1** [comment]
You are right. Actually the doom hook called `org-present-prettify-slide-h` sets a very wide margin and by removing or changing it I am able to control the width. Thanks
