### ISSUE TITLE
Starting the presentation gives an error

### ISSUE THREAD

**Issue by Lownin** [takaxp/org-tree-slide#54]
Using doom emacs railwaycat/emacsmacport/emacs-mac on macOS, when invoking org-tree-slide, I get an error &ldquo;Calling &lsquo;org-fold-core-region&rsquo; with missing SPEC&rdquo;
This can be skipped by invoking&#x2026;

    (setq org-fold-core-style  'overlay)

This does not seem to occur on Ubuntu using ppa:kelleyk/emacs

**Comment by takaxp** [comment]
I'm not sure but it is not the problem of org-tree-slide. It is probably because of org itself according to the following article.

https://adam.kruszewski.name/2022-05-08-org-publish-call-org-fold-core-region-error.html

**Comment by Lownin** [comment]
Is this new default with org 9.6 a bug in org-mode or should org-tree-slide be changed to accommodate the new default?

**Comment by takaxp** [comment]
If the change is a breaking from org 9.6, then I'll fix it in org-tree-slide.

**Comment by Lownin** [comment]
Sounds good.  Easy to work around for now.  Thank you so much for building this!

**Comment by Lownin** [comment]
That code seems to work for me to resolve the error. I can start the presentation without `(setq org-fold-core-style  'overlay)` using your change to contrib-present.el

**Comment by aisamu** [comment]
Fixed on doom on https://github.com/doomemacs/doomemacs/pull/7144 🥳
Thanks @takaxp!
