### ISSUE TITLE
[feature request] Start the presentation at a given heading

### ISSUE THREAD

**Issue by rdrg109** [takaxp/org-tree-slide#57]
# The context

Sometimes, a single Org Mode file contain multiple topics stored in different headlines. See example below

```
#+TITLE: Useful open-source utilities for undergraduate students

* Imagemagick
* mpv
* GNU Emacs
** Regular expressions

*** Basics
*** Special characters
*** Character classes

** Dired

*** Navigating through files
*** Common operations
```

Sometimes I'd like to start the presentation at one of those headings (e.g. `GNU Emacs/Regular expressions`) instead of the first one (e.g. `Imagemagick`).

From that I could notice, `org-tree-slide-mode` starts the presentation in the first heading found in the file.

# The current workaround

The only workaround I'm aware of is to execute `org-tree-slide-move-next-tree` (by default, mapped to `C->`) repeatedly until I show the headline that I'm interested in. This is cumbersome because sometimes the headline is >100 headlines below the current headline.

I use both small and big Org Mode files, so sometimes this is not a problem, but sometimes it is.

# The proposal

I propose we have an additional function for starting the presentation at a given heading. Thus, we avoid having to repeatedly execute `org-tree-slide-move-next-tree` repeatedly to make the current slide show the desired headline.

This new function could be called `org-tree-slide-mode-at-point`.

**Comment by takaxp** [comment]
Could you try to set `org-tree-slide-cursor-init` equal to `nil`? The user variable can control the cursor position when starting of your slideshow, yes, automatically move it to the first heading when the variable is `t`. So, after setting it to `nil`, move the cursor on the heading of `Regular expressions` as you kindly provided. And just activate `org-tree-slide-mode`. The presentation will start from the heading, not from the beginning of the file.

**Comment by rdrg109** [comment]
@takaxp Thanks for the quick reply. I didn't know that `org-tree-slide-cursor-init` could be used to set that behavior.

Before posting this issue, I read the docstring of all `defcustom` variables in `org-tree-slide.el`, but it wasn't clear to me that `org-tree-slide-cursor-init` could set that behavior. The first line of the docstring mentions `exit slideshow`, but it doesn't mention that it sets the starting slide.

https://github.com/takaxp/org-tree-slide/blob/3faa042393ebfe5699a3bffce775f039d7416ceb/org-tree-slide.el#L125-L131

I'd suggest that the docstring explicitly mentions that it also sets the starting slide. The first line in the docstring in the code block below is my suggestion. 

```elisp
(defcustom org-tree-slide-cursor-init t
  "Specify a cursor position at start and exit of the slideshow.
Non-nil: the cursor will move automatically to the head of buffer.
nil: keep the same position."
  :type 'boolean
  :group 'org-tree-slide)
```

**Comment by takaxp** [comment]
@rdrg109 Thank you for reading the docstrings. The variable was introduced at very early stage of development, and as you pointed the description is not good and also not reflect the actual function. I agree with your comment then it will be updated in the next update of this package. Thanks!

**Comment by rdrg109** [comment]
@takaxp Thanks for considering users' feedback for improving this project!

**Comment by takaxp** [comment]
@rdrg109 Yeah, thank your providing me an opportunity to improve this project :)
