### ISSUE TITLE
I don't see the slide number

### ISSUE THREAD

**Issue by refaelsh** [takaxp/org-tree-slide#65]
The documentation of the default value of "org-tree-slide-modeline-display" says I should see a slide number in the mode line, but I don't.

Please help :-)

**Comment by takaxp** [comment]
It's depend on context. Could you show your configuration regarding to "org-tree-slide-mode"?

**Comment by refaelsh** [comment]
,,,
  (use-package org-tree-slide
    :custom
    (org-tree-slide-cursor-init)
    (org-image-actual-width nil))
  (general-nmap "<leader>p" 'org-tree-slide-mode)
  (general-nmap "<leader>ro" 'read-only-mode)
  (define-key org-tree-slide-mode-map (kbd "C-<down>") 'org-tree-slide-move-next-tree)
  (define-key org-tree-slide-mode-map (kbd "C-<up>") 'org-tree-slide-move-previous-tree)
,,,

**Comment by takaxp** [comment]
It does not reproduce in my environment with your configuration...
<img width="688" alt="Screenshot_2023-05-13_at_1_19_11" src="https://github.com/takaxp/org-tree-slide/assets/136673/ce78ab40-aad0-4706-83eb-a25a3ec1bd42">

**Comment by refaelsh** [comment]
Maybe it's got something to do with the particular mode line I am using? I am using Doom mode line.

**Comment by takaxp** [comment]
Could you try `(setq org-tree-slide-modeline-display 'lighter)` instead of `'outside` which is the default.

**Comment by takaxp** [comment]
According to the official page of `doom-modeline`, enabling `doom-modeline-minor-modes` could work for Doom user. Another approach of setting `global-mode-string` may also work but in that case `org-tree-slide.el` shall be updated to support that.

**Comment by refaelsh** [comment]
When I am adding "doom-modeline-minor-modes" to my config, I can now see slide numbers, but I also see all the minor modes and that a lot and creates a lot of noise. Is there some other solution, please?

**Comment by refaelsh** [comment]
> Maybe it's got something to do with the particular mode line I am using? I am using Doom mode line.

Just wanna clarify, I don't use Doom Emacs, I use Vanilla Emacs and use the doom line as a package.

**Comment by takaxp** [comment]
A solution to this issue is here. I hope this code can be useful for `doom-modeline` user like you and also `Doom` Emacs user.

```
(defun my-add-slide-number ()
  (add-to-list 'global-mode-string
               '(:eval (concat "" (org-tree-slide--update-modeline) " "))))
(defun my-remove-slide-number ()
  (setq global-mode-string
        (remove '(:eval (concat "" (org-tree-slide--update-modeline) " "))
                global-mode-string)))

(add-hook 'org-tree-slide-play-hook #'my-add-slide-number)
(add-hook 'org-tree-slide-stop-hook #'my-remove-slide-number)

```

**Comment by refaelsh** [comment]
That solved the issue. Thank you very much.
