### ISSUE TITLE
Problem editing in slide mode

### ISSUE THREAD

**Issue by refaelsh** [takaxp/org-tree-slide#68]
I find myself often editing slides when in "org-tree-slide-play". I can edit anything except the org header line, the line that starts with a "*". Why is that so?

**Comment by takaxp** [comment]
Normally, you can add a new heading and also edit the heading. I guess "read-only-mode" could prevent something. Could you provide me more information to reproduce your case?

**Comment by refaelsh** [comment]
> I guess "read-only-mode" could prevent something

I am not in read-only mode.

> Could you provide me more information to reproduce your case?

Sure. Gladly. Here is the relevant part from my config:
```org
* Slides in Org Mode
#+begin_src emacs-lisp
  (use-package moom
    :init (moom-mode 1))

  (use-package org-tree-slide
    :hook ((org-tree-slide-play . (lambda() (moom-toggle-frame-maximized)))
           (org-tree-slide-stop . (lambda() (moom-toggle-frame-maximized))))
    :custom
    (org-tree-slide-cursor-init)
    (org-image-actual-width nil))
  (general-nmap "<leader>p" 'org-tree-slide-mode)
  (general-nmap "<leader>vm" 'view-mode)
  (define-key org-tree-slide-mode-map (kbd "C-<down>") 'org-tree-slide-move-next-tree)
  (define-key org-tree-slide-mode-map (kbd "C-<up>") 'org-tree-slide-move-previous-tree)
#+end_src
This solves an issue with slide numbers in Doom mode line. Taken from here: https://github.com/takaxp/org-tree-slide/issues/65.
#+begin_src emacs-lisp
  (defun my-add-slide-number ()
    (add-to-list 'global-mode-string
                 '(:eval (concat "" (org-tree-slide--update-modeline) " "))))
  (defun my-remove-slide-number ()
    (setq global-mode-string
          (remove '(:eval (concat "" (org-tree-slide--update-modeline) " "))
                  global-mode-string)))
  (add-hook 'org-tree-slide-play-hook #'my-add-slide-number)
  (add-hook 'org-tree-slide-stop-hook #'my-remove-slide-number)
#+end_src
```

**Comment by takaxp** [comment]
"view-mode" could prevent to edit headings but it is still hard for me to guess the exact reason. Maybe some conflicting with other packages are there. Is it possible to you to provide screen casting your case staring from entering "org-tree-slide-mode"? That may help my thinking.

**Comment by refaelsh** [comment]
> "view-mode" could prevent to edit headings

I am not in view-mode.

> Maybe some conflicting with other packages are there

Possible.

> Is it possible to you to provide screen casting your case staring from entering "org-tree-slide-mode"?

Sure. No problem. I will do it asap.

**Comment by refaelsh** [comment]
When I started making the screencast, the problem when away. Go figure.
Anyway, thank you very much for the help.
