### ISSUE TITLE
Add new slides while in "org-tree-slide-play" mode

### ISSUE THREAD

**Issue by refaelsh** [takaxp/org-tree-slide#69]
I find myself often editing slides when in "org-tree-slide-play". What I need is a functionality to add new slides while in "org-tree-slide-play" mode. Is this possible?

**Comment by takaxp** [comment]
If "org-tree-slide-play" means "org-tree-slide-mode" is activated, just add a new heading in the current slide.

**Comment by refaelsh** [comment]
> If "org-tree-slide-play" means "org-tree-slide-mode" is activated

Yes, I do. Sorry for the typo.

> just add a new heading in the current slide by "M-enter".

But then I would have two headings per slide, e.g., two slides in one slide. To solve it I would need to exit and re-enter slide mode. Is there any other solution please?

**Comment by refaelsh** [comment]
I understand. Thank you very much.
