### ISSUE TITLE
Change suggestions related to skip comments

### ISSUE THREAD

**Issue by ed9w2in6** [takaxp/org-tree-slide#70]
Migrated from a comment in #52

Hi, I have just started using `org-tree-slide` and I love it (way better than `org-present`) and I encounter this issue as well.
I had checked the develop branch and it seems good to be merged.
I had applied the code for my emacs and it matched my expected behaviour when used in `org-mode`

If we have to nitpick I guess these are possible changes:
1. Make `org-tree-slide-skip-comments-toggle` only callable in org-mode and fix its feedback and doc string.
```emacs-lisp
(defun org-tree-slide-skip-comments-toggle ()
  "Toggle show COMMENT item or not.
Toggle `org-tree-slide-skip-comments' between `t' and `nil'.
If `org-tree-slide-skip-comments' is `inherit',
then toggle between `inherit' and `nil'."
  (interactive)
  (if (eq major-mode 'org-mode)
      (progn
        ;; Sync
        (if (eq org-tree-slide-skip-comments 'inherit)
            (setq org-tree-slide--skip-comments-mode 'inherit)
          (when (eq org-tree-slide-skip-comments t)
            (setq org-tree-slide--skip-comments-mode t)))
        ;; Toggle
        (if (eq org-tree-slide--skip-comments-mode 'inherit)
            (if (eq org-tree-slide-skip-comments 'inherit)
                (setq org-tree-slide-skip-comments nil)
              (setq org-tree-slide-skip-comments 'inherit))
          (setq org-tree-slide-skip-comments
                (not org-tree-slide-skip-comments)))
        ;; Feedback
        (cond
         ((eq org-tree-slide-skip-comments nil)
          (message "COMMENT: SHOW"))
         ((eq org-tree-slide-skip-comments t)
          (message "COMMENT: HIDE"))
         ((eq org-tree-slide-skip-comments 'inherit)
          (message "COMMENT: HIDE (inherit)")))
        (setq org-tree-slide--slide-number
              (format " %s" (org-tree-slide--count-slide (point)))))
    ;; if not in org mode, org-complex-heading-regexp is nil which will fail
    ;; org-get-outline-path that is called by org-tree-slide--parent-commented-p
    ;; when doing org-tree-slide--count-slide.
    (message "Cannot toggle outside of org-mode.")))
```
This is because this interactive function calls `org-tree-slide--count-slide`, which will check for skipped headings.  Ultimately, `org-tree-slide--parent-commented-p` -> `org-get-outline-path` -> `org--get-outline-path-1` will be called.  `org--get-outline-path-1` expects `org-complex-heading-regexp` to be not `nil`, but it is `nil` when not in `org-mode`.  This means calling it outside of org-mode will produce error.
2. improve custom of `org-tree-slide-skip-comments` to sth like this:
```emacs-lisp
(defcustom org-tree-slide-skip-comments t
  "Specify to skip COMMENT item or not.
t: skip only headings with COMMENT, child headings without COMMENT will be shown.
nil: show headings even if it has COMMENT
inherit: skip headings with COMMENT and its child headings.
"
  :type
  '(choice
    (const :tag "Skip only headings with COMMENT" t)
    (const :tag "Show headings even if it has COMMENT" nil)
    (const
     :tag
     "Skip headings with COMMENT and its child headings"
     inherit))
  :group 'org-tree-slide)
```
3. Doc string for `org-tree-slide--get-parents` should use headings instead of headlines for consistency.
This: "Get parent ~headlines~ headings and concat them with DELIM."

~4. replace obsolete functions `org-show-entry` `org-show-siblings` and `point-at-bol`~ see: #61

**Comment by takaxp** [comment]
I think above three suggestions are covered in b535e26 and it was merged into the master branch. Many thanks to your comments.
