### ISSUE TITLE
When heading is active, level-1 headlines lose bullets

### ISSUE THREAD

**Issue by psionic-k** [takaxp/org-tree-slide#72]
Only affects the current slide headline, but level 1 headlines lose their bullet if the header is turned on.
```
[header]
* No bullet
** Bullet
* No bullet
** Bullet
*** Bullet
* No bullet
```

I also just noticed that the content has no header.  Only content is still showing level 1 bullets.

I want to customize these and fix some bugs.  Can you recommend which functions to look at to fix behavior?

**Comment by takaxp** [comment]
That is not a bug since the header is inserted by sacrificing the first asterisk.

**Comment by psionic-k** [comment]
I see.  The first header is being treated like a breadcrumb, but it's not a breadcrumb at that time:

### Before first slide:
![image](https://github.com/takaxp/org-tree-slide/assets/73710933/8fd1f437-fd22-4dbb-b891-c0c6a9cdf5da)

### After first slide:
![image](https://github.com/takaxp/org-tree-slide/assets/73710933/522397de-2019-4256-b262-8c5bfa1154d5)

It may be intentional, but I would like to customize this behavior.
