### ISSUE TITLE
issue with org-hide-emphasis-markers

### ISSUE THREAD

**Issue by emacsbliss** [takaxp/org-tree-slide#74]
It maybe somewhat related to https://github.com/takaxp/org-tree-slide/issues/56 but I'm not entirely sure.

Basically say I have following function to setup things before presentation starts:
```
(defun my/present-start ()
  (setq-local org-hide-emphasis-markers t))
```

and following one to revert the settings:
```
(defun my/present-stop ()
  (setq-local org-hide-emphasis-markers nil))
```

then configure package as below:
```
(use-package org-tree-slide
  :straight t
  :commands (org-tree-slide-mode)
  :custom
  (org-tree-slide-heading-emphasis t)
  (org-tree-slide-cursor-init t)
  (org-tree-slide-slide-in-effect t)
  (org-tree-slide-modeline-display nil)
  (org-tree-slide-activate-message " ")
  (org-tree-slide-deactivate-message " ")
  :config
  :hook (org-tree-slide-play . my/present-start)
  :hook (org-tree-slide-stop . my/present-stop))
```

Then we I start the presentation with command `org-tree-slide-mode`, I can still see things like `=key=`, which should be rendered as `key` (with different font face).

I tried `org-present` and it works. 

In my org mode configuration, I have `org-hide-emphasis-markers` set to `nil` by default since I only want this behavior during presentation.

`M-x emacs-version` produces this:
```
GNU Emacs 29.1.90 (build 1, aarch64-apple-darwin23.2.0, NS appkit-2487.30 Version 14.2 (Build 23C64)) of 2023-12-16
```

Could you help with this? Thanks!

**Comment by takaxp** [comment]
Are you using DOOM?

**Comment by emacsbliss** [comment]
no, I'm using configuration I build myself..

**Comment by takaxp** [comment]
Thanks, I'll try to investigate the issue.

**Comment by takaxp** [comment]
BTW, I'm currently using https://github.com/awth13/org-appear to hide the markups.

**Comment by takaxp** [comment]
The following code works for me.

1. enable font-lock-mode
2. call font-lock-flush after changing org-hide-emphasis-markers
3. use proper hooks org-tree-slide-play-hook and org-tree-slide-stop-hook (maybe not appropriate comment since I'm not familiar to use-package.el)

```lisp
(defun my-present-start ()
  (setq org-hide-emphasis-markers t)
  (font-lock-flush))
(defun my-present-stop ()
  (setq org-hide-emphasis-markers nil)
  (font-lock-flush))

(setq org-tree-slide-heading-emphasis t)
(setq org-tree-slide-cursor-init t)
(setq org-tree-slide-slide-in-effect t)
(setq org-tree-slide-modeline-display nil)
(setq org-tree-slide-activate-message " ")
(setq org-tree-slide-deactivate-message " ")

(add-hook 'org-tree-slide-play-hook #'my-present-start)
(add-hook 'org-tree-slide-stop-hook #'my-present-stop)
(add-hook 'org-mode-hook #'turn-on-font-lock)
```

**Comment by emacsbliss** [comment]
great, this works! thanks a lot!
