### ISSUE TITLE
Make org-tree-slide available in MELPA

### ISSUE THREAD

**Issue by CestDiego** [takaxp/org-tree-slide#9]
please, this would make installation and keeping up to date with it so much easier

**Comment by takaxp** [comment]
Thank you for your contribution!

**Comment by takaxp** [comment]
I just sent a pull request to the MELPA repository.
Please wait for their work.

**Comment by takaxp** [comment]
done.
https://github.com/milkypostman/melpa/commit/6160c259bc4bbcf3b98c220222430f798ee6463f
